### ISSUE TITLE
Jupyter for Kids on Open Collective

### ISSUE THREAD

**Issue by piamancini** [mikkokotila/jupyter4kids#8]
I'm one of the founders of open collective. We love your mission and we'd like to share your collective on our newsletter coming out today (sorry for the short notice). I'd be great if you can add some more information, a logo (maybe @mikkokotila you can add an avatar to your profile?) You can also edit your goals in opencollective.com/jupyter4kids/edit 
Let me know if I can help in any way, I'd love for your mission to succeed!

**Comment by mikkokotila** [comment]
@piamancini thanks so much for that :) I will work on profile now! Your kind words and support is very much appreciated.

**Comment by mikkokotila** [comment]
@piamancini  I have one question. I see that some pages have About as the first item on their page, how would I go about doing that? Also I would like to hide updates and events for now?

**Comment by piamancini** [comment]
that's what I'm seeing in the collective: 
<img width="1201" alt="screen shot 2018-09-19 at 1 00 40 pm" src="https://user-images.githubusercontent.com/3671070/45768896-0f78bb00-bc0c-11e8-8912-77b5980d3836.png"> Maybe try appending ?124 to refresh the cache?
Also, you can create titles with markdown H1 tags

**Comment by mikkokotila** [comment]
@piamancini Thanks :) Looks like that for me as well in Safari, but in Chrome for some reason I still get the updates and events on top (on Safari they are not visible).

**Comment by piamancini** [comment]
strange, my screenshot is from a chrome browser. It's looking nice! newsletter is coming out later today with this mention.

**Comment by mikkokotila** [comment]
@piamancini Thanks so much :) I will try to make a video in the near future that explains the project in a slightly more entertaining way. Will also think some t-shirt designs for perks. Thanks again for the help and speedy responses also :)
